spring.datasource.url=jdbc:mysql://localhost:3306/notes_ai
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

gemini.api.key=AQ.Ab8RN6L0Zn-qzdRtU77JXqoz4mcw69EQ170k16WAjp9XVJ_fpg